name: Build and test ShannonLoader

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reversing/ghidra/ShannonLoader

    env:
      GHIDRA_VERSION: ghidra_9.2.2_PUBLIC

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: grant-h/ShannonFirmware
        path: reversing/ghidra/ShannonLoader
    - name: Installing JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download Ghidra ${{ env.GHIDRA_VERSION }}
      run: wget -q https://ghidra-sre.org/${GHIDRA_VERSION}_20201229.zip
    - name: Unzip Ghidra
      run: unzip ${GHIDRA_VERSION}_20201229.zip
    - name: Build and pack extension
      run: GHIDRA_INSTALL_DIR=$(pwd)/${GHIDRA_VERSION} ./gradlew
    - name: Install extension to Ghidra
      run: unzip ./dist/ShannonLoader-*.zip -d ./${GHIDRA_VERSION}/Ghidra/Extensions
    - name: Test loader on firmware corpus
      run: ./scripts/ShannonFirmwareProcess.py $(pwd) ShannonProject ShannonFirmware/modem_files
