name: Build and test ShannonLoader

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reversing/ghidra/ShannonLoader
        
    env:
      ghidra-version: ghidra_9.2.2_PUBLIC
    steps:
    - uses: actions/checkout@v2
    #- uses: actions/checkout@v2
    #  with:
     #   repository: grant-h/ShannonFirmware
     #   path: reversing/ghidra/ShannonLoader
    - name: Installing JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download Ghidra ${env.ghidra-version}
      run: wget -q https://ghidra-sre.org/${env.ghidra-version}_20201229.zip
    - name: Unzip Ghidra
      run: unzip ${env.ghidra-version}_20201229.zip
    - name: Build and pack extension
      run: GHIDRA_INSTALL_DIR=$(pwd)/${env.ghidra-version} ./gradlew
    - name: Install extension to Ghidra
      run: unzip ./dist/ShannonLoader-*.zip -d ./${env.ghidra-version}/Ghidra/Extensions
      
  #  - name: Test Ghidra Headless
   #   run: ./ghidra_9.2.2_PUBLIC/support/analyzeHeadless /tmp/ testproject -loader ShannonLoader -noanalysis -overwrite -import ./ShannonFirmware/G800FXXU1CQB3_G800FOJV1CQB2_G800FXXU1CQB2_HOME_modem.bin
